import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RecoidContextProvider from "./recoilContextProvider";
import Appbar from "@/components/Appbar";
import InitUser from "@/components/InitUser";
import { Toaster } from "react-hot-toast";
import { AuthContextProvider } from './AuthContext'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> 
        <RecoidContextProvider>
          <AuthContextProvider>
          <Toaster />
          <Appbar /> 
          <InitUser />
          {children}
          </AuthContextProvider>
        </RecoidContextProvider>
      </body>
    </html>
  );
}
